name: pull_request-opened-synchronize-reopened-event

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out github-actions repo
        uses: actions/checkout@v4
        with:
          repository: aerius/github-actions
          path: aerius-github-actions
          ref: v1.1

      - uses: aerius/github-actions/events/pull_request-event-action@v1.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ROOT_POM_DIRECTORY: repo/source

      - uses: aerius/github-actions/extras/docker-build-action@v1.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_IMAGE_NAME: ${{ github.event.repository.name }}
          DOCKER_WORK_DIRECTORY: repo/source
          DOCKER_BUILD_PLATFORMS: linux/amd64,linux/arm64
